apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: auth
  name: auth
spec:
#  serviceName: keycloak-service
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: auth
  template:
    metadata:
      labels:
        application: auth
    spec:
      volumes:
      - name: tls-config-volume
        secret:
          secretName: tls-config
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      containers:
      - name: auth
        env:
        - name: DB_VENDOR
          value: h2
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_IMPORT
          value: ClientFhirServerRealm.json
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
#        envFrom:
#        - configMapRef:
#            name: environment-config
        image: __IMAGE__
        volumeMounts:
        - name: tls-config-volume
          mountPath: "/etc/x509/https"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            protocol: TCP
            containerPort: 8443
#          volumeMounts:
#          - name: jboss-persistent-storage
#            mountPath: /opt/jboss/keycloak/standalone/data/
        # Liveness probe configuration
        livenessProbe:
          httpGet:
            path: /auth/
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 5
        # Readiness probe configuration
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        # Startup probe configuration
        startupProbe:
          httpGet:
            path: /auth/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          failureThreshold: 60
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
#      volumes:
#      - name: jboss-persistent-storage
#        persistentVolumeClaim:
#          claimName: jboss-volumeclaim