apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: keycloak
  name: keycloak
spec:
  serviceName: keycloak-service
  replicas: 1
  selector:
    matchLabels:
      application: keycloak
  template:
    metadata:
      labels:
        application: keycloak
    spec:
      containers:
        - env:
            - name: DB_VENDOR
              value: h2
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_IMPORT
              value: /resources/ClientFhirServerRealm.json
          image: hkong2/keycloak
          name: keycloak
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: jboss-persistent-storage
            mountPath: /opt/jboss/keycloak/standalone/data/
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
      - name: jboss-persistent-storage
        persistentVolumeClaim:
          claimName: jboss-volumeclaim