apiVersion: v1
kind: Service
metadata:
  labels:
    application: auth
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 80
      targetPort: http
    - name: "https"
      port: 443
      targetPort: https
  selector:
    application: auth

