apiVersion: v1
kind: Service
metadata:
  labels:
    application: keycloak
  name: keycloak-service
spec:
  type: LoadBalancer
  ports:
    - name: "8180"
      port: 8180
      targetPort: 8080
  selector:
    application: keycloak

