variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  STAGING_ENABLED: "1"
  POSTGRES_ENABLED: "0"
  ROLLOUT_RESOURCE_TYPE: deployment
  INCREMENTAL_ROLLOUT_ENABLED: "0"

  DOCKER_IMAGE_VERSION: 19.03.1
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

  # Project Environment Settings NEEDS Update for new environment setup
  PROJECT_ID: "pri-auth-test"    #
  CLUSTER: "development" #TODO to be provisioned by DTP
  GSA_NAME: "gsa-priauth-service"
  KSA_NAME: "k8s-priauth-service"
  KUBE_NAMESPACE: "${CI_COMMIT_REF_SLUG}"
  ZONE: "us-central1-c"
  REGION: "us-central1"
  NETWORK: "drls"               #TODO to be provisioned by DTP


  # Pre-req: Project with Cluster + Agent + Ingress are setup.
  # To be changed depending on the deployment target environment
  # 'main' branch to be deployed into the 'demo' environment
  KUBE_CONTEXT: "gcp-solutions/hcls/claims-modernization/gitlab-gke:development"
  #KUBE_INGRESS_BASE_DOMAIN: 'papanca.com' #TODO

  CI_KUBERNETES_ACTIVE: 'true'



  CRD_IMAGE_TAG: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/crd/gcpdev:latest"

stages:
  - prepare_token
  - prepare_cluster
  - deploy
  - cleanup

# Needed to generate secret at cluster (one-time) to download images from GitLab repositories
# Alternative to consider is to add image pull secret to service account imagePullSecret TODO
# https://towardsdatascience.com/multiple-ways-to-create-kubernetes-secrets-33f97feaa499
gitlab prep token: #TODO: Maybe can be skipped? Generating token to pass it as a secret to GCP cluster to download Images from Gitlab private repositories
  environment: $CI_COMMIT_REF_SLUG
  stage: prepare_token
  image: docker:${DOCKER_IMAGE_VERSION}
  services:
  - docker:${DOCKER_IMAGE_VERSION}-dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cat $HOME/.docker/config.json > ${CI_PROJECT_DIR}/config.json
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/config.json
    expire_in: 1 day

prepare cluster:
  environment: $CI_COMMIT_REF_SLUG
  stage: prepare_cluster
  image: google/cloud-sdk
  script:
  - apk update && apk add git
  # Get CDS-Library to upload into the GCP Cloud Storage Bucket
  - git clone https://oauth2:$GR_TOKEN@gitlab.com/$CI_PROJECT_NAMESPACE/CDS-Library.git ${CI_PROJECT_DIR}/../CDS-Library
  # Get into the Cluster NAMESPACE context using GitLab Agent
  - kubectl config use-context $KUBE_CONTEXT
  - kubectl get namespace "$KUBE_NAMESPACE" 2>/dev/null || kubectl create namespace "$KUBE_NAMESPACE"
  - kubectl config set-context --current --namespace=$KUBE_NAMESPACE
  # Create Secret if not existing to PullImages from GitLab
  - kubectl get secret regcred --namespace=$KUBE_NAMESPACE 2>/dev/null ||
    kubectl create secret generic regcred --from-file=.dockerconfigjson=${CI_PROJECT_DIR}/config.json
    --type=kubernetes.io/dockerconfigjson --namespace=$KUBE_NAMESPACE
  - ${CI_PROJECT_DIR}/check_cluster.sh


#prepare cluster:
#  environment: $CI_COMMIT_REF_SLUG
#  stage: prepare
#  image: google/cloud-sdk
#  script:
#  - ${CI_PROJECT_DIR}/setup_cluster.sh

deploy to gke:
  environment: $CI_COMMIT_REF_SLUG
  stage: deploy
  image:
    name: google/cloud-sdk
  script:
  - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=$PROJECT_ID
  - gcloud projects describe "$PROJECT_ID"
  - kubectl config use-context $KUBE_CONTEXT
  - kubectl get namespace "$KUBE_NAMESPACE" 2>/dev/null || kubectl create namespace "$KUBE_NAMESPACE"
  - kubectl config set-context --current --namespace=$KUBE_NAMESPACE
  - ${CI_PROJECT_DIR}/deploy_services.sh
  - |
    if [ -n "$APPLICATION" ]; then
      echo "deployment is triggered by the $APPLICATION, executing on ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}, ${CI_BRANCH_TAG_NORMALIZED}"
      echo "Using the image $IMAGE_TAG built by the "$APPLICATION" pipeline"
      IMAGE_TAG=$IMAGE_TAG bash "${CI_PROJECT_DIR}/$APPLICATION/gcp/apply.sh"
    else
      echo "Internal Changes to manifest files, need to re-deploy all applications with images corresponding to this branch"
      echo "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}, $ ${CF_BRANCH_TAG_NORMALIZED}:latest"
      CRD_IMAGE_TAG=$CRD_IMAGE_TAG bash "${CI_PROJECT_DIR}/crd/gcp/apply.sh"
    fi


gcloud destroy:
  stage: cleanup
  image: google/cloud-sdk
  when: manual
  script:
  - "${CI_PROJECT_DIR}/delete_deployments.sh"

#deploy_review:
#  stage: deploy
#  script:
#  - echo "Deploy a review app"
#  environment:
#    name: review/$CI_COMMIT_REF_SLUG
#    url: https://$CI_ENVIRONMENT_SLUG.example.com
#  rules:
#  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#    when: never
#  - if: $CI_COMMIT_BRANCH