include:
  project: gcp-solutions/hcls/claims-modernization/gitlab-ci
  file: /.gitlab/ci/.deploy.gitlab-ci.yml

variables:
  GSA_NAME: "gsa-priauth-service" # Service Account Name to be created for crd application required for Cloud Storage Access for CDS-Library Access
  KSA_NAME: "k8s-priauth-service" # kubernetes service account for workload Identity for crd application
  GSA_EMAIL: $GSA_NAME@$PROJECT_ID.iam.gserviceaccount.com

  APPLICATION_NAMESPACE: ${CI_PROJECT_NAMESPACE}

  #Sharing same Agent, but could use different agents per environment
  #GITLAB_AGENT: ${CI_PROJECT_NAMESPACE}/gke-deploy-env:development
  KUBE_CONTEXT_DEMO: ${CI_PROJECT_NAMESPACE}/gke-deploy-env:development
  KUBE_CONTEXT_TEST: ${CI_PROJECT_NAMESPACE}/gke-deploy-env:development
  KUBE_CONTEXT_DEV: ${CI_PROJECT_NAMESPACE}/gke-deploy-env:development

  ######### Per Environment #############
  CLUSTER: "development"
  ZONE: "us-central1-c"
  REGION: "us-central1"
  PROJECT_ID_TEST: "pri-auth-cicd"
  PROJECT_ID_DEMO: "pri-auth-cicd"
  PROJECT_ID_DEV: "pri-auth-cicd"

stages:
- deploy
#- destroy

# Depends on SERVICE_ACCOUNT_FILE - JSON KEY File from ServiceAccount downloaded from GCP and saved as FILE Variable CI/CD Settings
.gcloud: &gcloud
#- echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ~/gcloud-service-key.json
#- gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
#- gcloud --quiet container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER
- gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT_FILE} --project=$PROJECT_ID
- kubectl config use-context $KUBE_CONTEXT
- kubectl get namespace "$NAMESPACE" 2>/dev/null || kubectl create namespace "$NAMESPACE"
- kubectl config set-context --current --namespace=$NAMESPACE
- kubectl config current-context
- gcloud --quiet container clusters get-credentials $CLUSTER --region $REGION


gcloud destroy:
  stage: cleanup
  image: google/cloud-sdk
  when: manual
  script:
  - PROJECT_ID=$PROJECT_ID BUCKET=$BUCKET bash "${CI_PROJECT_DIR}/crd/gcp/delete.sh"






