version: '3.6'
services:
  keycloak:
    container_name: keycloak    
    # command: ["-Djboss.http.port=8180"]
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/resources/ClientFhirServerRealm.json
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data/
      - '../test-ehr/src/main/resources/ClientFhirServerRealm.json:/resources/ClientFhirServerRealm.json'
    image: hkong2/keycloak

  # Create crd container
  test-ehr: # Name of our service
    container_name: test-ehr
    ports: # Port binding to host from docker container
      - '8080:8080' # Bind port 3000 of host to 3000 of container
    build: 
      context: ../test-ehr
      dockerfile: Dockerfile.dev 
    volumes:
      - /test-ehr/.gradle
      - /test-ehr/build
      - /test-ehr/target
      - /test-ehr/bin


  # Create crd container
  crd: # Name of our service
    build: 
      context: ../CRD
      dockerfile: Dockerfile.dev 
    container_name: crd
    ports: # Port binding to host from docker container
      - "8090:8090" # Bind port 3000 of host to 3000 of container
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}
    volumes:
      - /CRD/.gradle


  # Create crd container
  crd-request-generator: # Name of our service
    build: 
      context: ../crd-request-generator
      dockerfile: Dockerfile.dev 
    container_name: crd-request-generator
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
      - "3001:3001"
    volumes:
      - /home/node/app/node_modules
      - /home/node/app/db-data


  # Create crd container
  dtr: # Name of our service
    build: 
      context: ../dtr
      dockerfile: Dockerfile.dev     
    container_name: dtr
    ports: # Port binding to host from docker container
      - "3005:3005" # Bind port 3000 of host to 3000 of container
    volumes:
      - /home/node/app/node_modules
      - /home/node/app/databaseData

volumes:
  keycloak-data:
