#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

get_service_file(){
  ENVIRONMENT=$1
  case "$ENVIRONMENT" in
    demo) echo "$SERVICE_ACCOUNT_FILE_DEMO"
       ;;
    test) echo "$SERVICE_ACCOUNT_FILE_TEST"
       ;;
    development) echo "$SERVICE_ACCOUNT_FILE_DEV"
      ;;
  esac
}

get_bucket(){
  ENVIRONMENT=$1
  case "$ENVIRONMENT" in
    demo) echo "gs://${PROJECT_ID}-cql"
       ;;
    test) echo "gs://${PROJECT_ID}-cql-test"
       ;;
    development) echo "gs://${PROJECT_ID}-cql-dev"
      ;;
  esac
}

if [ -z "$ENVIRONMENT" ]; then
  echo 'Error ENVIRONMENT not set, aborting'
  exit
fi

SERVICE_ACCOUNT_FILE=${SERVICE_ACCOUNT_FILE:-$(get_service_file "$ENVIRONMENT")}
export SERVICE_ACCOUNT_FILE

KUBE_NAMESPACE=$NAMESPACE
export KUBE_NAMESPACE

BUCKET=${BUCKET:-$(get_bucket "$ENVIRONMENT")}
export BUCKET