apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: crd-request-generator-service-backend-config
spec:
  healthCheck:
    type: HTTP
    port: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "crd-request-generator-service-backend-config"}'
  labels:
    application: crd-request-generator
  name: __CRD_REQUEST_GENERATOR_SERVICE__
spec:
  type: ClusterIP
  ports:
    - name: "app"
      port: 80
      targetPort: 3000
    - name: "public-keys"
      port: 3001
      targetPort: 3001
  selector:
    application: crd-request-generator
