apiVersion: v1
kind: Service
metadata:
  labels:
    app: crd
  name: crd-service
spec:
  type: LoadBalancer
  ports:
    - name: "8090"
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: crd
