apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: prior-auth-old
  name: prior-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      application: prior-auth-old
  template:
    metadata:
      labels:
        application: prior-auth-old
    spec:
      containers:
        - image: __IMAGE__
          name: prior-auth
          env:
          - name: TOKEN_BASE_URI
            valueFrom:
              configMapKeyRef:
                name: pa-config
                key: token_base_uri
          ports:
            - containerPort: 9015
          resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always