apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: dtr
  name: dtr
spec:
  serviceName: dtr-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: dtr
  template:
    metadata:
      labels:
        application: dtr
    spec:
      containers:
        - image: __IMAGE__
          env:
          - name: REACT_APP_PA_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: dtr-config
                key: pa_base_url
          name: dtr
          ports:
            - containerPort: 3005
          volumeMounts:
          - name: lowdb-persistent-storage
            mountPath: /home/node/app/databaseData
          resources:
            requests:
              cpu: 1
              memory: 4Gi
              ephemeral-storage: 4Gi
            limits:
              cpu: 2
              memory: 8Gi
              ephemeral-storage: 5Gi
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: lowdb-persistent-storage
        persistentVolumeClaim:
          claimName: lowdb-volumeclaim
      restartPolicy: Always
