apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: dtr-service-backend-config
spec:
  healthCheck:
    type: HTTP
    requestPath: /register
    port: 3005
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "dtr-service-backend-config"}'
  labels:
    application: dtr
  name: dtr-service
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 3005
      targetPort: http
  selector:
    application: dtr