apiVersion: v1
kind: Service
metadata:
  labels:
    application: dtr
  name: dtr-service
spec:
  type: LoadBalancer
  ports:
    - name: "3005"
      port: 3005
      targetPort: 3005
  selector:
    application: dtr
