apiVersion: v1
kind: Service
metadata:
  labels:
    application: prior-auth-new
  name: prior-auth-service-new
spec:
  type: LoadBalancer
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    application: prior-auth-new
