apiVersion: v1
kind: Service
metadata:
  labels:
    application: crd-request-generator
  name: crd-request-generator
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    application: crd-request-generator
