apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: crd-service-backend-config
spec:
  healthCheck:
    type: HTTP
    requestPath: /index
    port: 8090
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "crd-service-backend-config"}'
  labels:
    app: crd
  name: __CRD_SERVICE__
spec:
  type: ClusterIP
  ports:
    - name: "8090"
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: crd

