#!/usr/bin/env bash
UTILS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN=$1
GCP=$2

source "$BIN"/SET
echo "**** Deploying $APPLICATION to GKE $CLUSTER cluster of project $PROJECT_ID ****"

"$UTILS"/../get_services.sh

"$BIN"/docker_build

docker push "$IMAGE":"$VERSION"

"$GCP"/rollout.sh

IP=$("$UTILS/get_service_external_ip_port" "$APPLICATION"-service)
echo "External IP for $APPLICATION-service " "$IP"

echo "**** Done! ****"