#!/usr/bin/env bash
BIN="$1"

source "$BIN"/SET
if docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "$TAG"
then
  echo "Using already built image $TAG"
  "$BIN"/docker_stop
else
  "$BIN"/docker_build
fi


