#!/usr/bin/env bash
BIN="$1"

source "$BIN"/SET
TAG="$IMAGE:$VERSION"
if docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "$IMAGE_TAG"
then
  echo "Using already built image $IMAGE_TAG"
  "$BIN"/docker_stop
else
  "$BIN"/docker_build
fi


