#!/usr/bin/env bash
BIN=$1

source "$BIN/SET"
TAG="$IMAGE":"$VERSION"
LATEST="$IMAGE":"latest"

CID=$(docker images "$IMAGE_TAG" --format "{{.Repository}}:{{.Tag}}")
if [ -z "$CID" ]; then
  echo "Building Image $IMAGE_TAG ..."
  "$BIN/docker_build"
else
  echo "Using already built image  $IMAGE_TAG ..."
fi

docker push "$IMAGE_TAG"
docker push "$LATEST"