#!/usr/bin/env bash
SERVICE=$1

function getExternalIp() {
  IP=$(kubectl get service "$SERVICE" -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null)
}

if ! kubectl get service "$SERVICE"  &> /dev/null; then
  exit
fi

getExternalIp
while [ -z "$IP" ]
do
   #echo "Waiting for external IP to get assigned to the service $APPLICATION...."
   sleep 10
   getExternalIp
done

echo "$IP"
#kubectl get service "$APPLICATION"