#!/usr/bin/env bash
BIN=$1
GCP=$2

source "$BIN"/SET

"$GCP"/apply.sh

if kubectl get deployment "$APPLICATION" --ignore-not-found=true  -n "$KUBE_NAMESPACE" | grep "$APPLICATION"; then
  echo "Rollout restart for $APPLICATION deployment ..."
  kubectl rollout restart deployment "$APPLICATION" -n "$KUBE_NAMESPACE"
fi
