#!/usr/bin/env bash

ZONE='us-central1-c'
REGION='us-central1'
NETWORK='drls'
CLUSTER='prior-auth'

get_service_file(){
  ENVIRONMENT=$1
  case "$ENVIRONMENT" in
    demo) echo "$SERVICE_ACCOUNT_FILE_DEMO"
       ;;
    test) echo "$SERVICE_ACCOUNT_FILE_TEST"
       ;;
    development) echo "$SERVICE_ACCOUNT_FILE_DEV"
      ;;
  esac
}

# In case SERVICE_ACCOUNT_FILE_$ENVIRONMENT is set, use that value. otherwise fall back to SERVICE_ACCOUNT_FILE
SERVICE_ACCOUNT_FILE_ENV=$(get_service_file "$ENVIRONMENT")
if [ -n "$SERVICE_ACCOUNT_FILE_ENV" ]; then
  SERVICE_ACCOUNT_FILE=$SERVICE_ACCOUNT_FILE_ENV
fi
export SERVICE_ACCOUNT_FILE


BUCKET_NAME=${BUCKET_NAME:-${PROJECT_ID}-cql-${KUBE_NAMESPACE}}
export BUCKET_NAME
BUCKET="gs://$BUCKET_NAME"
export BUCKET


